[package]
name = "search-engine"
version = "0.1.0"
edition = "2024"
authors = ["Morteza Raeisi <raeisimv@outlook.com>"]

[dependencies]
aes-gcm = "0.10"
async-fs = "2.1"
serde = { version = "1" }
serde_cbor = "0.11"
futures-lite = "2.6.0"